export OS_USER_ID="{{ swift.user_id }}"
export OS_PASSWORD="{{ swift.password }}"
export OS_PROJECT_NAME="{{ swift.project_name }}"
export OS_PROJECT_ID="{{ swift.project_id }}"
export OS_AUTH_URL="{{ swift.auth_url }}"
export OS_REGION_NAME="{{ swift.region_name }}"
export OS_AUTH_VERSION="{{ swift.auth_version }}"
export OS_IDENTITY_API_VERSION="{{ swift.identity_api_version }}"
